project:
  name: Geomagnetical Index Prediction
  version: 0.1

dataset:
  omni_variables: ["B_Total", "BZ_GSE", "flow_speed", "Vx", "T", "Pressure", "E_Field", "proton_density",]
  auroral_variables: ["AE_INDEX", "AL_INDEX", "AU_INDEX"]
  index_prediction: "AE Index"
  time_range:
    start: "1995-01-01"
    end: "2018-12-31"

  scaler_type: "robust"

hyparameter:
  model:
    type: "TKAN"
    lr: 0.001
    drop:
  constant:
      Epoch: 300
      delay_length: [30, 60, 180, 300, 600]

    